version: "3.3"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    restart: always
    env_file:
      ./.env
    ports:
      - "5432:5432"
  app:
    container_name: app
    image: videot4pe/spacestory
    restart: always
    env_file:
      ./.env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  pgadmin-data: