export enum ICONS {
  GitHub = 'GitHub',
  MedalFirst = 'MedalFirst',
  MedalSecond = 'MedalSecond',
  MedalThird = 'MedalThird',
  MedalOther = 'MedalOther',
  Close = 'Close',
  Envelope = 'Envelope',
  EnvelopeAdd = 'EnvelopeAdd',
  EnvelopeLock = 'EnvelopeLock',
  EmptyAvatar = 'EmptyAvatar',
  Play = 'Play',
  Pause = 'Pause',
  Info = 'Info',
  Check = 'Check',
  Warning = 'Warning',
}
