name: deploy-spacestory
on: push
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: docker build -t videot4pe/spaceshooter . --platform linux/amd64
      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      - name: Docker push
        run: docker push videot4pe/spaceshooter
  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          data: "{ 'data': 'data'}"
